### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/base-basil-test-case#119]
- [x] webignition/symfony-panther-dom-crawler-navigator#73
- [x] webignition/webdriver-element-inspector#44
- [x] webignition/webdriver-element-mutator#20
